# Generated by Django 3.1.4 on 2021-01-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
