# Generated by Django 3.1.5 on 2021-01-27 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210127_2208'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentform',
            table='pictures',
        ),
    ]
